# CONFIGURACION DE BASE DE DATOS
spring.datasource.url=jdbc:postgresql://localhost:5432/natymoon
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.port=8080

# JWT
app.jwt.secret=NatymooSuperSecretKeyParaJWT2026CambiarEnProduccion123456789
app.jwt.expiration-ms=86400000
app.jwt.cookie-name=natymoo_token
app.jwt.cookie-secure=false

# CORS - Frontend
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://appassets.androidplatform.net
